apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-prom
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: my-cluster-config/kube-prometheus-stack
    repoURL: 'https://github.com/grey1001/helm.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
