apiVersion: batch/v1
kind: Job
metadata:
  name: apache-bench-job
spec:
  template:
    spec:
      containers:
      - name: apache-bench-container
        image: httpd
        command: ["ab", "-n", "500000", "-c", "1000", "http://sample-nginx-service.default.svc.cluster.local/"]
      restartPolicy: Never
  backoffLimit: 4 # Adjust the backoff limit as needed
