apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
  namespace: default
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi