apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql
  namespace: default
  labels:
    app:  mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  mysql
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mysql
        image:  mysql:8.0-debian
        
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11
        ports:
        - containerPort:  3306
          name:  mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: usermanagement-dbcreation-script
            mountPath: /docker-entrypoint-initdb.d
           
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
             claimName: ebs-mysql-pv-claim
        - name: usermanagement-dbcreation-script
          configMap: 
            name: usermanagement-dbcreation-script
      restartPolicy: Always